-- MySQL Script generated by MySQL Workbench
-- Thu Dec 12 20:57:05 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema OpenFoodsDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OpenFoodsDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OpenFoodsDB` DEFAULT CHARACTER SET utf8 ;
USE `OpenFoodsDB` ;

-- -----------------------------------------------------
-- Table `OpenFoodsDB`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OpenFoodsDB`.`Category` ;

CREATE TABLE IF NOT EXISTS `OpenFoodsDB`.`Category` (
  `idCategory` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(254) NULL,
  `name` VARCHAR(1024) NULL,
  `url` VARCHAR(1024) NULL,
  `is_active` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`idCategory`),
  UNIQUE INDEX `idCategorie_UNIQUE` (`idCategory` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OpenFoodsDB`.`Store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OpenFoodsDB`.`Store` ;

CREATE TABLE IF NOT EXISTS `OpenFoodsDB`.`Store` (
  `idStore` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(254) NULL,
  `name` VARCHAR(1024) NULL,
  `url` VARCHAR(1024) NULL,
  `is_active` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`idStore`),
  UNIQUE INDEX `idStore_UNIQUE` (`idStore` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OpenFoodsDB`.`Brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OpenFoodsDB`.`Brand` ;

CREATE TABLE IF NOT EXISTS `OpenFoodsDB`.`Brand` (
  `idBrand` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(254) NULL,
  `name` VARCHAR(1024) NULL,
  `url` VARCHAR(1024) NULL,
  `is_active` TINYINT NULL,
  PRIMARY KEY (`idBrand`),
  UNIQUE INDEX `idBrand_UNIQUE` (`idBrand` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OpenFoodsDB`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OpenFoodsDB`.`Product` ;

CREATE TABLE IF NOT EXISTS `OpenFoodsDB`.`Product` (
  `idProduct` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NULL DEFAULT 'NoCode',
  `label` VARCHAR(1024) NULL DEFAULT 'Undefined Name',
  `url` VARCHAR(1024) NULL DEFAULT 'No Url',
  `is_active` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`idProduct`),
  UNIQUE INDEX `idProduct_UNIQUE` (`idProduct` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OpenFoodsDB`.`Product_has_Store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OpenFoodsDB`.`Product_has_Store` ;

CREATE TABLE IF NOT EXISTS `OpenFoodsDB`.`Product_has_Store` (
  `Product_idProduct` INT UNSIGNED NOT NULL,
  `Product_Category_idCategory` INT UNSIGNED NOT NULL,
  `Product_Brand_idBrand` INT UNSIGNED NOT NULL,
  `Store_idStore` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Product_idProduct`, `Product_Category_idCategory`, `Product_Brand_idBrand`, `Store_idStore`),
  INDEX `fk_Product_has_Store_Store1_idx` (`Store_idStore` ASC) VISIBLE,
  INDEX `fk_Product_has_Store_Product1_idx` (`Product_idProduct` ASC, `Product_Category_idCategory` ASC, `Product_Brand_idBrand` ASC) VISIBLE,
  CONSTRAINT `fk_Product_has_Store_Product1`
    FOREIGN KEY (`Product_idProduct`)
    REFERENCES `OpenFoodsDB`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_has_Store_Store1`
    FOREIGN KEY (`Store_idStore`)
    REFERENCES `OpenFoodsDB`.`Store` (`idStore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OpenFoodsDB`.`Category_has_Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OpenFoodsDB`.`Category_has_Product` ;

CREATE TABLE IF NOT EXISTS `OpenFoodsDB`.`Category_has_Product` (
  `Category_idCategory` INT UNSIGNED NOT NULL,
  `Product_idProduct` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Category_idCategory`, `Product_idProduct`),
  INDEX `fk_Category_has_Product_Product1_idx` (`Product_idProduct` ASC) VISIBLE,
  INDEX `fk_Category_has_Product_Category1_idx` (`Category_idCategory` ASC) VISIBLE,
  CONSTRAINT `fk_Category_has_Product_Category1`
    FOREIGN KEY (`Category_idCategory`)
    REFERENCES `OpenFoodsDB`.`Category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Category_has_Product_Product1`
    FOREIGN KEY (`Product_idProduct`)
    REFERENCES `OpenFoodsDB`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OpenFoodsDB`.`Search`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OpenFoodsDB`.`Search` ;

CREATE TABLE IF NOT EXISTS `OpenFoodsDB`.`Search` (
  `Category_idCategory` INT UNSIGNED NOT NULL,
  `Product_idProduct` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Category_idCategory`, `Product_idProduct`),
  INDEX `fk_Category_has_Product1_Product1_idx` (`Product_idProduct` ASC) VISIBLE,
  INDEX `fk_Category_has_Product1_Category1_idx` (`Category_idCategory` ASC) VISIBLE,
  CONSTRAINT `fk_Category_has_Product1_Category1`
    FOREIGN KEY (`Category_idCategory`)
    REFERENCES `OpenFoodsDB`.`Category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Category_has_Product1_Product1`
    FOREIGN KEY (`Product_idProduct`)
    REFERENCES `OpenFoodsDB`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OpenFoodsDB`.`Product_has_Brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OpenFoodsDB`.`Product_has_Brand` ;

CREATE TABLE IF NOT EXISTS `OpenFoodsDB`.`Product_has_Brand` (
  `Product_idProduct` INT UNSIGNED NOT NULL,
  `Brand_idBrand` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Product_idProduct`, `Brand_idBrand`),
  INDEX `fk_Product_has_Brand_Brand1_idx` (`Brand_idBrand` ASC) VISIBLE,
  INDEX `fk_Product_has_Brand_Product1_idx` (`Product_idProduct` ASC) VISIBLE,
  CONSTRAINT `fk_Product_has_Brand_Product1`
    FOREIGN KEY (`Product_idProduct`)
    REFERENCES `OpenFoodsDB`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_has_Brand_Brand1`
    FOREIGN KEY (`Brand_idBrand`)
    REFERENCES `OpenFoodsDB`.`Brand` (`idBrand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
